### ISSUE TITLE
edxapp | bundle install task failing with " Bundler::GemfileNotFound"

### ISSUE THREAD

**Issue by DivyaMangotra** [openedx-unsupported/configuration#2794] opened 2016-02-22 09:01 UTC
I am deploying a multi-node openedx cluster. As  a part of my deployment I am running the edxapp role. As a part of the edxapp role, deployment.yml is faling with the following error-
`TASK: [edxapp | bundle install] ***********************************************
failed: [IP] => {"changed": true, "cmd": "bundle install --binstubs", "delta": "0:00:00.462722", "end": "2016-02-22 06:25:17.954711", "rc": 10, "start": "2016-02-22 06:25:17.491989", "warnings": []}
stdout: Bundler::GemfileNotFound
`

**Comment by nedbat** [comment] 2016-02-22 11:08
Duplicate of #2787

**Closed as completed by nedbat** 2016-02-22 11:08 UTC
