### ISSUE TITLE
Install fails, problem with python post-post requirements - opaque-keys

### ISSUE THREAD

**Issue by vietdungiitb** [openedx-unsupported/configuration#2434] opened 2015-11-01 02:10 UTC
I tried to install edx Ubuntu 12.04 64 bit following the wiki but it has problem as below. 
Anyone can help me? please,
Thank you

TASK: [edxapp | install python post-post requirements] ************************
failed: [localhost] => (item=/edx/app/edxapp/edx-platform/requirements/edx/githu                                                                                                                     b.txt) => {"changed": true, "cmd": "/edx/app/edxapp/venvs/edxapp/bin/pip install                                                                                                                      -i https://pypi.python.org/simple --exists-action w --use-mirrors -r /edx/app/e                                                                                                                     dxapp/edx-platform/requirements/edx/github.txt ", "delta": "0:00:50.415518", "en                                                                                                                     d": "2015-11-01 08:53:30.895199", "item": "/edx/app/edxapp/edx-platform/requirem                                                                                                                     ents/edx/github.txt", "rc": 1, "start": "2015-11-01 08:52:40.479681"}
stderr: fatal: Needed a single revision
Unable to find current revision in submodule path 'ext/spec'
stdout: You are using pip version 6.0.8, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
DEPRECATION: --use-mirrors has been deprecated and will be removed in the future                                                                                                                     . Explicit uses of --index-url and/or --extra-index-url is suggested.
Collecting git+https://github.com/pmitros/pyfs.git@96e1922348bfe6d99201b9512a9ed                                                                                                                     946c87b7e0b (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (l                                                                                                                     ine 27))
  Cloning https://github.com/pmitros/pyfs.git (to 96e1922348bfe6d99201b9512a9ed9                                                                                                                     46c87b7e0b) to /tmp/pip-O4yijL-build
  Could not find a tag or branch '96e1922348bfe6d99201b9512a9ed946c87b7e0b', ass                                                                                                                     uming commit.
Collecting git+https://github.com/hmarr/django-debug-toolbar-mongo.git@b0686a76f                                                                                                                     1ce3532088c4aee6e76b9abe61cc808 (from -r /edx/app/edxapp/edx-platform/requiremen                                                                                                                     ts/edx/github.txt (line 29))
  Cloning https://github.com/hmarr/django-debug-toolbar-mongo.git (to b0686a76f1                                                                                                                     ce3532088c4aee6e76b9abe61cc808) to /tmp/pip-TLlc6L-build
  Could not find a tag or branch 'b0686a76f1ce3532088c4aee6e76b9abe61cc808', ass                                                                                                                     uming commit.
    Installed /tmp/pip-TLlc6L-build/.eggs/versiontools-1.9.1-py2.7.egg
Obtaining django-pipeline from git+https://github.com/cyberdelia/django-pipeline                                                                                                                     .git@1.5.3#egg=django-pipeline (from -r /edx/app/edxapp/edx-platform/requirement                                                                                                                     s/edx/github.txt (line 11))
  Updating /edx/app/edxapp/venvs/edxapp/src/django-pipeline clone (to 1.5.3)
Obtaining django-wiki from git+https://github.com/edx/django-wiki.git@cd0b2b3199                                                                                                                     7afccde519fe5b3365e61a9edb143f#egg=django-wiki (from -r /edx/app/edxapp/edx-plat                                                                                                                     form/requirements/edx/github.txt (line 12))
  Updating /edx/app/edxapp/venvs/edxapp/src/django-wiki clone (to cd0b2b31997afc                                                                                                                     cde519fe5b3365e61a9edb143f)
  Could not find a tag or branch 'cd0b2b31997afccde519fe5b3365e61a9edb143f', ass                                                                                                                     uming commit.
Obtaining django-oauth2-provider from git+https://github.com/edx/django-oauth2-p                                                                                                                     rovider.git@0.2.7-fork-edx-5#egg=django-oauth2-provider (from -r /edx/app/edxapp                                                                                                                     /edx-platform/requirements/edx/github.txt (line 13))
  Updating /edx/app/edxapp/venvs/edxapp/src/django-oauth2-provider clone (to 0.2                                                                                                                     .7-fork-edx-5)
    /edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/setuptools/di                                                                                                                     st.py:294: UserWarning: The version specified ('0.2.7-fork-edx-5') is an invalid                                                                                                                      version, this may not work as expected with newer versions of setuptools, pip,                                                                                                                      and PyPI. Please see PEP 440 for more details.
      "details." % self.metadata.version
Obtaining djangorestframework-oauth from git+https://github.com/edx/django-rest-                                                                                                                     framework-oauth.git@f0b503fda8c254a38f97fef802ded4f5fe367f7a#egg=djangorestframe                                                                                                                     work-oauth (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (li                                                                                                                     ne 14))
  Updating /edx/app/edxapp/venvs/edxapp/src/djangorestframework-oauth clone (to                                                                                                                      f0b503fda8c254a38f97fef802ded4f5fe367f7a)
  Could not find a tag or branch 'f0b503fda8c254a38f97fef802ded4f5fe367f7a', ass                                                                                                                     uming commit.
Obtaining mongodb-proxy from git+https://github.com/edx/MongoDBProxy.git@25b9909                                                                                                                     7615bda06bd7cdfe5669ed80dc2a7fed0#egg=mongodb_proxy (from -r /edx/app/edxapp/edx                                                                                                                     -platform/requirements/edx/github.txt (line 15))
  Updating /edx/app/edxapp/venvs/edxapp/src/mongodb-proxy clone (to 25b99097615b                                                                                                                     da06bd7cdfe5669ed80dc2a7fed0)
  Could not find a tag or branch '25b99097615bda06bd7cdfe5669ed80dc2a7fed0', ass                                                                                                                     uming commit.
Collecting nltk==2.0.6 from git+https://github.com/edx/nltk.git@2.0.6#egg=nltk==                                                                                                                     2.0.6 (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 16                                                                                                                     ))
  Cloning https://github.com/edx/nltk.git (to 2.0.6) to /tmp/pip-build-69svZq/nl                                                                                                                     tk
Obtaining pystache-custom from git+https://github.com/dementrock/pystache_custom                                                                                                                     .git@776973740bdaad83a3b029f96e415a7d1e8bec2f#egg=pystache_custom-dev (from -r /                                                                                                                     edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 17))
  Updating /edx/app/edxapp/venvs/edxapp/src/pystache-custom clone (to 776973740b                                                                                                                     daad83a3b029f96e415a7d1e8bec2f)
  Could not find a tag or branch '776973740bdaad83a3b029f96e415a7d1e8bec2f', ass                                                                                                                     uming commit.
  Complete output from command /usr/bin/git submodule update --init --recursive                                                                                                                      -q:

---

  Command "/usr/bin/git submodule update --init --recursive -q" failed with erro                                                                                                                     r code 1 in /edx/app/edxapp/venvs/edxapp/src/pystache-custom
failed: [localhost] => (item=/edx/app/edxapp/edx-platform/requirements/edx/local                                                                                                                     .txt) => {"changed": true, "cmd": "/edx/app/edxapp/venvs/edxapp/bin/pip install                                                                                                                      -i https://pypi.python.org/simple --exists-action w --use-mirrors -r /edx/app/ed                                                                                                                     xapp/edx-platform/requirements/edx/local.txt ", "delta": "0:00:06.843773", "end"                                                                                                                     : "2015-11-01 08:53:37.830746", "item": "/edx/app/edxapp/edx-platform/requiremen                                                                                                                     ts/edx/local.txt", "rc": 1, "start": "2015-11-01 08:53:30.986973"}
stdout: You are using pip version 6.0.8, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
DEPRECATION: --use-mirrors has been deprecated and will be removed in the future                                                                                                                     . Explicit uses of --index-url and/or --extra-index-url is suggested.
Obtaining file:///edx/app/edxapp/edx-platform (from -r /edx/app/edxapp/edx-platf                                                                                                                     orm/requirements/edx/local.txt (line 2))
Obtaining file:///edx/app/edxapp/edx-platform/common/lib/calc (from -r /edx/app/                                                                                                                     edxapp/edx-platform/requirements/edx/local.txt (line 3))
Obtaining file:///edx/app/edxapp/edx-platform/common/lib/capa (from -r /edx/app/                                                                                                                     edxapp/edx-platform/requirements/edx/local.txt (line 4))
Obtaining file:///edx/app/edxapp/edx-platform/common/lib/chem (from -r /edx/app/                                                                                                                     edxapp/edx-platform/requirements/edx/local.txt (line 5))
Obtaining file:///edx/app/edxapp/edx-platform/common/lib/dogstats (from -r /edx/                                                                                                                     app/edxapp/edx-platform/requirements/edx/local.txt (line 6))
Obtaining file:///edx/app/edxapp/edx-platform/common/lib/safe_lxml (from -r /edx                                                                                                                     /app/edxapp/edx-platform/requirements/edx/local.txt (line 7))
Obtaining file:///edx/app/edxapp/edx-platform/common/lib/sandbox-packages (from                                                                                                                      -r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 8))
Obtaining file:///edx/app/edxapp/edx-platform/common/lib/symmath (from -r /edx/a                                                                                                                     pp/edxapp/edx-platform/requirements/edx/local.txt (line 9))
Obtaining file:///edx/app/edxapp/edx-platform/common/lib/xmodule (from -r /edx/a                                                                                                                     pp/edxapp/edx-platform/requirements/edx/local.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): setuptools in /edx/app                                                                                                                     /edxapp/venvs/edxapp/lib/python2.7/site-packages (from Open-edX==0.5->-r /edx/ap                                                                                                                     p/edxapp/edx-platform/requirements/edx/local.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): pyparsing==2.0.1 in /e                                                                                                                     dx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from calc==0.2->-r /edx/                                                                                                                     app/edxapp/edx-platform/requirements/edx/local.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): numpy in /edx/app/edxa                                                                                                                     pp/venvs/edxapp/lib/python2.7/site-packages (from calc==0.2->-r /edx/app/edxapp/                                                                                                                     edx-platform/requirements/edx/local.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): scipy in /edx/app/edxa                                                                                                                     pp/venvs/edxapp/lib/python2.7/site-packages (from calc==0.2->-r /edx/app/edxapp/                                                                                                                     edx-platform/requirements/edx/local.txt (line 3))
Collecting nltk<3.0 (from chem==0.1.1->-r /edx/app/edxapp/edx-platform/requireme                                                                                                                     nts/edx/local.txt (line 5))
  Using cached nltk-2.0.5.tar.gz
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0                                                                                                                     .6.21.tar.gz
    Extracting in /tmp/tmpT2o6Rq
    Now working in /tmp/tmpT2o6Rq/distribute-0.6.21
    Building a Distribute egg in /tmp/pip-build-0nIqe0/nltk
    /tmp/pip-build-0nIqe0/nltk/distribute-0.6.21-py2.7.egg
Requirement already satisfied (use --upgrade to upgrade): dogapi in /edx/app/edx                                                                                                                     app/venvs/edxapp/lib/python2.7/site-packages (from dogstats-wrapper==0.1->-r /ed                                                                                                                     x/app/edxapp/edx-platform/requirements/edx/local.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): lxml in /edx/app/edxap                                                                                                                     p/venvs/edxapp/lib/python2.7/site-packages (from safe-lxml==1.0->-r /edx/app/edx                                                                                                                     app/edx-platform/requirements/edx/local.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): defusedxml in /edx/app                                                                                                                     /edxapp/venvs/edxapp/lib/python2.7/site-packages (from safe-lxml==1.0->-r /edx/a                                                                                                                     pp/edxapp/edx-platform/requirements/edx/local.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): sympy in /edx/app/edxa                                                                                                                     pp/venvs/edxapp/lib/python2.7/site-packages (from symmath==0.1->-r /edx/app/edxa                                                                                                                     pp/edx-platform/requirements/edx/local.txt (line 9))
Collecting docopt (from XModule==0.1->-r /edx/app/edxapp/edx-platform/requiremen                                                                                                                     ts/edx/local.txt (line 10))
  Using cached docopt-0.6.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): path.py in /edx/app/ed                                                                                                                     xapp/venvs/edxapp/lib/python2.7/site-packages (from XModule==0.1->-r /edx/app/ed                                                                                                                     xapp/edx-platform/requirements/edx/local.txt (line 10))
Collecting webob (from XModule==0.1->-r /edx/app/edxapp/edx-platform/requirement                                                                                                                     s/edx/local.txt (line 10))
  Using cached WebOb-1.5.1-py2.py3-none-any.whl
Collecting opaque-keys (from XModule==0.1->-r /edx/app/edxapp/edx-platform/requi                                                                                                                     rements/edx/local.txt (line 10))
  Could not find any downloads that satisfy the requirement opaque-keys (from XM                                                                                                                     odule==0.1->-r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 10)                                                                                                                     )
  Some externally hosted files were ignored as access to them may be unreliable                                                                                                                      (use --allow-external opaque-keys to allow).
  No distributions at all found for opaque-keys (from XModule==0.1->-r /edx/app/                                                                                                                     edxapp/edx-platform/requirements/edx/local.txt (line 10))

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/edx_sandbox.retry

localhost                  : ok=174  changed=35   unreachable=0    failed=1

**Comment by aabouzaid** [comment] 2015-11-12 19:54
I got the same error! It's so weird! Sometimes appeared and not!

**Comment by a-nassif** [comment] 2015-11-16 14:42
Any update on this? A fresh checkout from release will get the same error.

**Comment by aabouzaid** [comment] 2015-11-16 14:58
BTW, it seems like a connection issue, something happen for one of previous steps (Ansible tasks) leads to this issue (I got HTTP 408 timeout error from Github)

Sometimes when I retry it again works fine, sometimes I need to remove "/edx/" directory (and stop any service depends on this directory) to make it work!

**Comment by AMKamel** [comment] 2016-01-27 08:51
I confirm that the same issue is still not resolved!

**Comment by nedbat** [comment] 2016-04-14 21:02
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.

**Comment by aabouzaid** [comment] 2016-04-15 10:34
@nedbat 
Thanks for your reply, but this isn't a question! It's more like an issue somewhere or a bug!

**Comment by nedbat** [comment] 2016-04-15 17:40
@AAbouZaid I don't have this issue when I try the Native installation instructions.  To figure out what is different, I need this from you:  1) what vagrant box did you use to install ubuntu 12.04, or how did you install it, if not with vagrant?  2) The contents of your Vagrantfile.  3) The entire output of the installation process, including the commands you typed, starting with "vagrant up".

**Comment by aabouzaid** [comment] 2016-04-15 21:12
@nedbat It was appearing randomly. The point here it's an issue at the end. And someone opened this issue to be fixed in upstream, so no one tries to debug it again :-)

I really would like to help, but unfortunately I'm no longer working on that project. I don't have any access for what you asked right now (5 moths are a little bit long time as you know).

Thanks a lot

**Comment by nedbat** [comment] 2016-04-17 16:31
@AAbouZaid I understand it's a problem, but I don't know how to reproduce it.  The issue starts with:

> stderr: fatal: Needed a single revision

I don't know what is causing that error.  If anyone can reproduce the error, please let me know.

**Comment by nedbat** [comment] 2016-04-17 16:34
I'm closing this issue now for two reasons: we cannot reproduce it, and we have since released Dogwood to replace Cypress.  Please feel free to re-open the issue if you can reproduce it.

**Closed as completed by nedbat** 2016-04-17 16:34 UTC
